baseURL = "http://zeroryuu.github.io/"
languageCode = "en-us"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  DateFormat = "2006-01-02"
  YearFormat = "2006"
  MonthFormat = "01-02"
  Fancybox = true


